language: ruby

rvm:
#  - 2.3.1
  - jruby-9.1.6.0

env:
  - DB=postgres

before_script: bundle install

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/

before_script:
  - postgres -e 'create database demo_test'
